background = "#fdfdfd"
surface = "#ffffff"
panel = "#e8e8e8"
text = "#333333"
text_secondary = "#555555"
hint = "#888888"
menu = "#444444"
accent = "#0066cc"
accent_text = "#ffffff"
highlight = "#3a9ee5"
target = "#ff69b4"
warning = "#ffaa00"
warning_text = "#202020"
success = "#44cc44"
success_text = "#ffffff"
error = "#dd3333"
error_text = "#ffffff"
inactive_text = "#777777"
inactive_bg = "#dddddd"
crumb_a = "#f0f0f0"
crumb_b = "#e0e0e0"
