[package]
name = "glues-core"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Headless state management module for Glues Notes"

[dependencies]
gluesql.workspace = true
gluesql-mongo-storage = "0.16.3"
async-recursion.workspace = true
thiserror = "1.0.61"
async-trait = "0.1"
uuid = { version = "1.10", features = ["v7"] }
strum_macros = "0.26.4"

[dev-dependencies]
tokio = { version = "1.41.0", features = ["macros", "rt"] }
